### ISSUE TITLE
What is root password?

### ISSUE THREAD

**Issue by KashifHK123** [scottyhardy/docker-remote-desktop#10]
Hello, I need a root password to install my required programs. You didn't share the root password, Can you please share it?

**Comment by MRzNone** [comment]
Probably this line has some hint:

https://github.com/scottyhardy/docker-remote-desktop/blob/master/entrypoint.sh#L5

**Comment by MRzNone** [comment]
I was able to change the pass word via logging in as root and change password for user `ubuntu`.

```
docker exec -u 0 -it remote-desktop /bin/bash # log in the container as root
passwd ubuntu # change password
```

**Comment by DarkAxi0m** [comment]
Rather than the changing the password, I've found it better/easier to install sudo.

```
docker exec -u 0 -it remote-desktop /bin/bash    
apt update   
apt install sudo    
usermod -aG sudo ubuntu
```

Then logout and back in to the desktop and you can run root commands with sudo

```
sudo bash  
sudo apt update    
etc
```

**Comment by scottyhardy** [comment]
Hi all,

There is no root password set, unless there's one set in the ubuntu image(s) (which I'm pretty sure it's not).  I thought I'd already added sudo to this image - looks like I haven't though so I can do that.
