### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by develmac** [scottyhardy/docker-remote-desktop#12]
**Is your feature request related to a problem? Please describe.**
It would be great to run this image on ARM64 based systems like Raspberries or Apple devices

**Describe the solution you'd like**
Run it on ARM.

**Describe alternatives you've considered**
Build image on own.

**Comment by scottyhardy** [comment]
I still only have an Intel based Mac, so I'm not sure if just building for ARM is all I need to do for Apple silicon... I'll have to research it, but it's something I'll keep in mind while I'm looking for a new host for my automated builds

**Comment by scottyhardy** [comment]
Hi @maconic 

I’ve just added arm64 to the builds, which from what I’ve read should enable Apple M1 Macs to run the container without needing Rosetta to emulate an Intel CPU, as well as other ARM-based machines.

**Comment by develmac** [comment]
@scottyhardy great, thank you! I don't have an ARM Mac yet, but I have a k8s cluster on ARM (Raspberry4), I will give it a try!

**Comment by develmac** [comment]
I can report that it nicely runs on ARM64! Tested it on my k8s cluster, running on Raspberry4s. Btw. can I somehow have multiple connections from RDP? Can I mount a volume to make things persistent? I guess I will dig more into this now that it runs! THX!

**Comment by scottyhardy** [comment]
Hi @maconic - thanks for the feedback, glad it's working for you.  I've been playing around a little with k8s lately and using pvc to persist the user files is one of the things on my list of to-dos.  RDP can service multiple concurrent users with their own sessions if that's what you're asking - that's one of the (many) reasons why I opted for RDP over VNC.

**Comment by develmac** [comment]
@scottyhardy Yes it works great, really cool! Thank you! I am using NFS as a persistence engine on my k8s and will try it as a home directory for the image! I was thinking about connecting multiple sessions for the same user (kind of like a kiosk usage), but I guess that is not really the intended way of RDP. The great news for me is that RDP works really well on Samsung Tizen TVs.
