### ISSUE TITLE
Pulseaudio only gets loaded after connecting 1 time to the rdp

### ISSUE THREAD

**Issue by humanperzeus** [scottyhardy/docker-remote-desktop#8]
**Describe the bug**

**To Reproduce**
1. Create the container and add any script that uses AUDIO. Start the Container and DONT connect via RDP.

**Expected behavior**
Virtual Audio device is loaded and usable WITHOUT the need to connecting one time via rdp

**Additional context**
I need to connect always 1 time via rdp, that the virtual dummy device gets created and then I can start my script that uses sound. If I don't connect via rdp, there is no dummy virtual sound available that can be used but I don't want to be forced to connect every time first.
Can we change that somehow that the container creates the dummy device from beginning even when not connecting to the container via rdp?

**Comment by scottyhardy** [comment]
I'm not really sure what you're attempting to do here... If you're just wanting "dummy" sound as in just going to null, you can use:
```
rm -f /var/lib/xrdp-pulseaudio-installer/module-xrdp-{sink,source}.so
```
From my understanding, the pulseaudio daemon should auto-spawn when you access the audio - that's part of what I configure in the Dockerfile.  I'd suggest trying pacat -vvv /udev/random to test the status of the audio device.  Other than that, your use case doesn't sound like something that many others would use.  If you come up with a solution and want it include, just send through a pull request and I'll happily include.
